### ISSUE TITLE
Upgrade to .NET 5.0

### ISSUE THREAD

**Issue by sebastianbk** [RimuTec/AspNetCore.SpaServices.Extensions#14]
Hi,

First of all, thank you so much for making this repository. Like many others, I am also impacted by Microsoft's decision to deprecate `UseWebpackDevMiddleware` so, for me, the work you have put into this repository is really valuable.

I'm trying to upgrade my application to .NET 5.0 but I can't quite seem to get HMR working. Is there any chance you could upgrade this sample to 5.0?

Best,
Sebastian

**Comment by ManfredLange** [comment]
@sebastianbk I can't promise anything but I'll look into how this example could work in .NET 5.0.

**Comment by ManfredLange** [comment]
A first rough test shows that all I had to do was changing the target framework in both the nuget package and the sample proejct from "netcoreapp3.1" to "net5.0". No other changes were required to make it work just as before.

Having said that, next I'll need to check if I can have the nuget package target multiple framework.

**Comment by ManfredLange** [comment]
@sebastianbk I just published a new release of this nuget package that I tested for the two target frameworks netcoreapp3.1 as well as net5.0.

All you have to do is change the target framework in your web application to whichever target framework you want to use. For the SampleWebApp in this repo, no further changes are required. It's possible to just switch back and forth between netcoreapp3.1 and net5.0 without code change.

Let me know if this meets the enhancement you suggested. Unless I hear otherwise, I intend to close this issue no earlier than 04 Jan 2021.

Thank you for filing this issue! Contributions like yours are extremely valuable and help foster the open-source community.

**Comment by ManfredLange** [comment]
There are now also two sample web applications in this repo: One targeting netcoreapp3.1 and one targeting net5.0. Both reference the package `RimuTec.AspNetCore.SpaServices.Extensions`. The version is 2.2.0 as of writing.

**Comment by ManfredLange** [comment]
As I haven't heard otherwise, I'll assume this issues has been resolved.

@sebastianbk Thank you again for filing this issue, Sebastian. Valuable contributions like yours are an important element for the open source community.
